wcコマンドの作成
zamami/ruby-practices pull request #7
Opened 2023-06-05 01:14 UTC by zamami

wcコマンドを作成しました。
レビューよろしくお願いします。

2023-06-11 15:52 UTC, u1tnk requested changes
まずは PR全体のやり方の部分の対応をお願いします。
wc本体ですが、一部コメントしてますが、共通化ができていないです。
とりあえず動作する状態まで来たのは良いことなので、ここから同じような動作をしているところを一つにする。もしくはメソッドに切り分けて全体を短く、分かりやすくする方法を考えてみてください。

2023-06-11 15:52 UTC, u1tnk commented on 05.wc/hoge.txt
> +1
テスト用のデータは動作確認のためならコミットしない方が良いですね。
テストプログラムを書いているなら必要ですが、その場合も testディレクトリを作って入れるなど、本体のプログラムとは別とわかるようにしてください。

2023-06-11 15:52 UTC, u1tnk commented on 05.wc/ls.rb
> +# frozen_string_literal: true
wcコマンドのプラクティスなので ls用のプログラムが差分に表示されているのはおかしいです。

2023-06-11 15:52 UTC, u1tnk commented on 05.wc/wc.rb
> +def option_word_count(files, options)
word_count とoption以外が一緒なので共通化するべきです。 word_count も lwc全て あるときはまったく一緒の動作ですし。

2023-06-18 16:46 UTC, u1tnk requested changes
だいぶ良くなりました。
細かい指摘のみです！

2023-06-18 16:46 UTC, u1tnk commented on 05.wc/wc.rb
> +def option_value?(options, option)
これはメソッド名から考えると特殊な仕様(オプションが一つも指定されていないときは有効)が入っているのに名前が一般的なので名前が良くないですね。
名前を考えてみてください。

2023-06-19 03:27 UTC, u1tnk requested changes

2023-06-19 03:27 UTC, u1tnk commented on 05.wc/wc.rb
> +def option_select_or_no_option(options, option)
内容そのままではありますし、前のものよりは正確で良いと思いますが、このメソッドを見ても何故こうなるんだろう？？となってしまうと思います。

この項目を出力するのか？という目的を表した名前の方が簡潔になって良いと思います。
また、指摘漏れましたがbooleanで返すメソッドの場合 `hoge?` と?で終わる慣習がrubyにはあるので付けるようにしましょう。

2023-06-19 14:16 UTC, zamami commented on 05.wc/wc.rb
> +def option_value?(options, option)
コメントありがとうございます。
メソッド名だけで意味が伝わるように名前を修正してみます！

2023-06-19 14:16 UTC, zamami commented on 05.wc/wc.rb
> +def option_select_or_no_option(options, option)
レビューありがとうございます。
名前の付け方はいまだにどうやったら良いかわからないので、
「この項目を出力するのか？という目的を表した名前」
このアドバイスがとても勉強になりました。

2023-06-19 14:16 UTC, zamami commented on 05.wc/wc.rb
> +def option_select_or_no_option(options, option)
今回のメソッドは、
「すべてのオプションが無いか、または特定のオプションが選択されているか？」
という意味ですので、これをそのままメソッド名にして
「all_options_unselected_or_specific_option_selected?」。

もしくは、オプション無しか、オプションが決まっているのか？
という意味を込めた「no_options_or_determin_option?」
など考えてみました。

これらの命名は「この項目を出力するのか？という目的を表した名前」に習っているでしょうか？

2023-06-19 14:21 UTC, zamami commented on 05.wc/wc.rb
> +def option_select_or_no_option(options, option)
もしくはメソッドの中身の意味ではなく、素直に「output_this_line?」というのもありなのでしょうか？

2023-06-20 02:54 UTC, u1tnk commented on 05.wc/wc.rb
> +def option_select_or_no_option(options, option)
> もしくはメソッドの中身の意味ではなく、素直に「output_this_line?」というのもありなのでしょうか？

そういう意味でした。
メソッドの中身をそのまま表現するメソッド名もよく使われますが、長くなると難しくなるので適さなくなってきます。
ただ` output_this_line?` は lineでは無いのでそこは変更しましょう。あとは thisなどの代名詞は英語的にあった方が良いかもしれませんが、情報量が無いのでできれば省略したいです。
また、keyword 引数を使って引数名含めて分かりやすくなればさらに良いですね。 `output_xxx?(option: x)` のようにすると引数のoptionによって出力するかを判定しているのが分かります。

2023-06-21 12:16 UTC, zamami commented on 05.wc/wc.rb
> +def option_select_or_no_option(options, option)
>メソッドの中身をそのまま表現するメソッド名もよく使われますが、長くなると難しくなるので適さなくなってきます。なるほど。勉強になりました。
以上を踏まえてキーワード引数を用いた`output_count?`と命名してみました。

2023-06-21 16:28 UTC, u1tnk approved these changes
OKです！

2023-06-30 08:57 UTC, merged